EJERS=ejer1 ejer2 ejer3 hola_mundo

todos: $(EJERS)

ejer1: ejer1.c
	gcc ejer1.c -o ejer1

ejer2: ejer2.c
	gcc ejer2.c -o ejer2

ejer3: ejer3.c hola_mundo
	gcc ejer3.c -o ejer3

hola_mundo: hola_mundo.c
	gcc hola_mundo.c -o hola_mundo
