all: countprimes countprimes_parallel

countprimes: countprimes.c
	gcc -o countprimes countprimes.c -lm

countprimes_parallel: countprimes_parallel.c
	gcc -o countprimes_parallel countprimes_parallel.c -lm
