# objetivo: dependencia(s)
# <tab>	cmd1
# <tab> cmd2
# .
EJERS=ejer1 ejer2 ejer3

todos: $(EJERS)

ejer1: ejer1.c
	gcc ejer1.c -o ejer1

ejer2: ejer2.c
	gcc ejer2.c -o ejer2

ejer3: ejer3.c
	gcc ejer3.c -o ejer3

ps:
	ps --user lsandova f
