BINS:= jugadores_domino mensajes1 mensajes2 mensajesints
all: $(BINS)

jugadores_domino: jugadores_domino.c
	gcc -o jugadores_domino jugadores_domino.c

mensajes1: mensajes1.c
	gcc -o mensajes1 mensajes1.c

mensajes2: mensajes2.c
	gcc -o mensajes2 mensajes2.c

mensajesints: mensajesints.c
	gcc -o mensajesints mensajesints.c

clean:
	rm -f $(BINS)
